//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractId { get; set; }
        public string ContractAddress { get; set; }
        public string ParentContractAdress { get; set; }
        public Nullable<int> HupCount { get; set; }
        public Nullable<int> ContractBalance { get; set; }
        public Nullable<int> ContractBond { get; set; }
        public Nullable<int> RouteFoundBond { get; set; }
        public string BuyerAddress { get; set; }
        public string SellerAddress { get; set; }
        public string ContractStatus { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> RouteFoundDateTime { get; set; }
        public Nullable<System.DateTime> RouteConfirmDateTime { get; set; }
        public Nullable<int> ExpiresInMinutes { get; set; }
    }
}
