//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public int NodeId { get; set; }
        public string PublicKey { get; set; }
        public Nullable<int> PositionX { get; set; }
        public Nullable<int> PositionY { get; set; }
        public Nullable<bool> IsBaseStation { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsRunning { get; set; }
    }
}
