//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whisper
    {
        public long Id { get; set; }
        public string FromNode { get; set; }
        public string ToNode { get; set; }
        public string ContractAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> MessageRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public string Notes { get; set; }
    }
}
